### ISSUE TITLE
[Suggestion] Allow to examine while holding shift

### ISSUE THREAD

**Issue by vitorebom** [Skretzo/runelite-plugins#10]
Add a toggleable option that allows us to examine things while holding shift.  
I used to rely on examining items to check GE price and while I LOVE the examine missclick never happening again I'm missing this easy price check.

**Comment by Skretzo** [comment]
I have now added a toggleable option to bypass removing examing while holding shift. This will be live in the client when it has been reviewed, typically in a week or so.
