### ISSUE TITLE
SUGGESTION - Remove option

### ISSUE THREAD

**Issue by wgh5** [Skretzo/runelite-plugins#11]
I love this plugin so much the way it removes the most useless option :cancel: and the examine feature. What about an option to remove the :remove: option while in the POH? And even maybe an option to remove the :walk here: as well for the cleanest option menu.

**Comment by Skretzo** [comment]
Removing the `Remove` option in the POH and the `Walk here` option was added in [version 1.4](https://github.com/Skretzo/runelite-plugins/commit/50218644fd8d9c8c5edfe1db0d0e7c1eda27e10b), and is now live in the client.
