### ISSUE TITLE
Hiding POH Remove option also hides the right-click Remove option in the equipment screen while in POH

### ISSUE THREAD

**Issue by fuzxi** [Skretzo/runelite-plugins#13]
![2022-08-13-18-20-34](https://user-images.githubusercontent.com/33790641/184518644-5004ebbe-06dd-4cc3-964e-9f176d213924.png)
![2022-08-13-18-20-30](https://user-images.githubusercontent.com/33790641/184518645-d7b59a34-2a8d-4c10-8843-0ba480a48524.png)

**Comment by Skretzo** [comment]
This has been [fixed](https://github.com/Skretzo/runelite-plugins/commit/f97c0ea114e7a570c0e1857c1598999ee3d0c044) and is now live in the client. Restart your client to fetch the update if you have not done so in the last 3 hours or so.
