### ISSUE TITLE
Ability to export / import

### ISSUE THREAD

**Issue by SandroVA** [Skretzo/runelite-plugins#14]
Would be really nice to have. Sharing with my friends is slightly time consuming.

**Comment by Skretzo** [comment]
Are you referring to the radius marker plugin? That should be doable. I can probably add a small copy to clipboard button on each marker in the panel

**Comment by SandroVA** [comment]
Oh sorry! Yes the radius marker plugin

**Comment by Skretzo** [comment]
This was added in [version 1.5](https://github.com/Skretzo/runelite-plugins/commit/c13d90b6addc35d344145e037ee95fc341526b1b) and is now live in the client.
Restart your client to fetch the update.
![illustration](https://user-images.githubusercontent.com/53493631/194666107-a9ef2c71-6f87-4f84-be27-04e9397cbc21.png)
