### ISSUE TITLE
[Suggestion] Add ability to hide 'Follow' and 'Trade with' on "No Examine" -plugin

### ISSUE THREAD

**Issue by ZeiZeiii** [Skretzo/runelite-plugins#19]
Ability to toggle these on with friends or clan mates would also be cool

**Comment by Skretzo** [comment]
The official Old School RuneScape [Third Party Client Guidelines](https://secure.runescape.com/m=news/third-party-client-guidelines?oldschool=1) contains a list of unacceptable features, wherein the following example is listed:
> Reorders or removes player-based options, such as 'Trade with'

I don't really know why this is forbidden, but it means I sadly cannot implement your suggestion. Our only option is to kindly request that the Old School Team re-evaluates whether this rule is still necessary or not.
