### ISSUE TITLE
no-examine: Suggestion to remove "Cancel"

### ISSUE THREAD

**Issue by Popedigoz** [Skretzo/runelite-plugins#20]
Who ever pressed "cancel" to cancel? I always just click anywhere on the screen BUT the "cancel" button to cancel.

**Comment by Skretzo** [comment]
The plugin already has the ability to remove the `Cancel` option:
![config-remove-cancel](https://user-images.githubusercontent.com/53493631/218166442-3be90dbe-3df9-4026-b280-4e0d1d8c8338.png)
![illustration-no-cancel](https://user-images.githubusercontent.com/53493631/218166630-39f35823-47e0-4a96-b5fe-dc83158e1ffe.png)
Please let me know if the option does not work as intended.

**Comment by Popedigoz** [comment]
> 

Oh wow, my bad - should've actually installed first before to see. Seems to be working just fine. Maybe plugin name change is in order?

**Comment by Skretzo** [comment]
> Maybe plugin name change is in order?

There is already a better plugin out there called `Custom Menu Swapper` that can remove any user-specified menu option, so I don't think I will bother to improve or rename this plugin
