### ISSUE TITLE
Export visible markers simply exports all markers

### ISSUE THREAD

**Issue by zombiezrule** [Skretzo/runelite-plugins#21]
I'm not sure if it's the intended action, but the export all visible markers button simply exports all markers.

It would be nice if I could search to show only a few radius markers, and then only export those ones, so I don't have to copy it to a notepad and remove all other markers if I want to share only a few of them (instead of sharing every single marker I have).

**Comment by Skretzo** [comment]
> the export all visible markers button simply exports all markers

Is it really not working for you? It only respects the top level visibility button next to the delete marker button, not the sub level visibilities.

> It would be nice if I could search to show only a few radius markers, and then only export those ones

This is a good suggestion. I will improve the exporting to respect search terms, filtering and the usual visibility.

**Comment by zombiezrule** [comment]
Maybe I've been misinterpreting it - I initially thought that export all visible markers would be exporting the ones that I can see near me, or that it would export markers that were visible in the sidebar following searching. If it's just markers that you have enabled, then that makes sense.

Thanks for taking on board the searching export idea!

**Comment by Skretzo** [comment]
As of [version 1.7](https://github.com/Skretzo/runelite-plugins/commit/275125aec15cab48495ff27659074256f7262728) exporting markers now respects search terms and/or filtering.

|Filter|Info|Illustration|
|:-----|:----|:------------|
|**All**|Every marker will be exported|![filter-all](https://user-images.githubusercontent.com/53493631/226219032-63c0ed5d-e550-4526-9307-90aed59078bf.png)|
|**Region**|Only markers in the current world region <br>(64 x 64 tile area) will be exported. <br>This is somewhat equivalent to what <br>you are actually able to see in-game|![filter-region](https://user-images.githubusercontent.com/53493631/226219167-2c4013e3-77db-4dc9-8d1a-31a3063dc989.png)|
|**Visible**|All markers that are enabled will be exported|![filter-visible](https://user-images.githubusercontent.com/53493631/226218612-3ee22afe-01f4-484f-9854-d17c9304383c.png)|
|**Hidden**|All disabled markers will be exported|![filter-hidden](https://user-images.githubusercontent.com/53493631/226218808-7c25e0a0-ac54-4de8-a081-fecf04b3605b.png)|

Searching can be combined with the filtering to export very specific markers.
