### ISSUE TITLE
Combat roll - defensive range roll correct?

### ISSUE THREAD

**Issue by notCascar** [Skretzo/runelite-plugins#24]
Is it correct that the `DEFENSIVE_RANGED` roll takes the ranged level, rather than the defence level? I thought only magic defence was calculated differently?

For ref here: https://github.com/Skretzo/runelite-plugins/blob/combat-roll/src/main/java/com/combatroll/CombatRollPlugin.java#L221

**Comment by Skretzo** [comment]
You are correct, this was a mistake. I have now changed the ranged defence roll to use the defence level instead of the ranged level. The update will be live in the client in a week or two once it has been reviewed by the RuneLite developers.
