### ISSUE TITLE
Radius marker show on minimap doesn't account for zoom.

### ISSUE THREAD

**Issue by emiljensen2** [Skretzo/runelite-plugins#28]
The show on minimap for radius markers won't account for the zoom level of your minimap, so if you zoom in/out it will not be in the correct place. it's always correct on the world map no matter the zoom amount.
I always play with zoomed out minimap so it's very apparent.
Runelite 1.10.9.1
launcher 2.5.0
Radius marker 1.8

**Comment by Skretzo** [comment]
This was fixed in plugin version 1.9.3.
