### ISSUE TITLE
[Line Markers] Broken link

### ISSUE THREAD

**Issue by MESLewis** [Skretzo/runelite-plugins#29]
This page https://runelite.net/plugin-hub/show/line-markers links to this "plugin wiki page" https://raw.githubusercontent.com/Skretzo/wiki/Line-Markers which is returning a 400 error

**Comment by Skretzo** [comment]
I believe this is an issue related to the runelite webpage and not my plugin readme, as the link in my readme is https://github.com/Skretzo/runelite-plugins/wiki/Line-Markers, which is the correct one.

**Comment by Skretzo** [comment]
This was fixed in https://github.com/runelite/runelite.net/commit/72d7a02facbb7093bb86549d1d6f6c7210a6f951
