### ISSUE TITLE
Vardorvis Airborne Axes changed from NPC to Game Object?

### ISSUE THREAD

**Issue by Mandredwhatdoyoumeanmynameistaken** [Skretzo/runelite-plugins#31]
I ran into an Issue at Vardorvis today as the Airborne Axes no longer use their old NPC ID (12227), instead they are considered game objects according to the Identificator Plugin. They also get unique IDs every time they spawn which makes it impossible to mark them with Radius markers
![ShareX_AScaosjSsK](https://github.com/Skretzo/runelite-plugins/assets/39282108/eb176cfb-c7f0-47b1-a82f-f422e571ca2a)
![ShareX_6bIoORRk1j](https://github.com/Skretzo/runelite-plugins/assets/39282108/c020d625-a7f2-4750-93dd-944984619abc)

Yet somehow it still works if you use the old NPC ID with better npc highlight

**Comment by Skretzo** [comment]
I'm not really sure what is going on with the ID of those axes, but as of version 1.9 of the Radius Marker plugin from last week it is no longer possible to mark NPCs without a name. This includes the swinging Vardorvis axes, and is a deliberate change to make it easier for me to maintain this plugin for future boss releases, as Jagex generally dislikes dynamic markers on newly released boss content. As you pointed out you should be able to use the Better NPC Highlight plugin to achieve the same marker, so feel free to use that plugin instead.

**Comment by Mandredwhatdoyoumeanmynameistaken** [comment]
Thanks for clearing that up
