### ISSUE TITLE
Clicking the color picker in the sidebar menu under certain conditions causes the dialogue box to appear outside of the screen and become unmovable and unclosable

### ISSUE THREAD

**Issue by b-licorice** [Skretzo/runelite-plugins#32]
Couldn't seem to replicate this issue with any color picker buttons within the RL plugin config panel. Also couldn't replicate it with other similar plugins that also have a sidepanel that contains color picker buttons (e.g. Boss Health Indicators), so it appears to be an issue with Radius Markers.

Conditions to replicate issue:

1. The game window is near the top edge of the screen
2. There are enough radius markers in the sidepanel that you can scroll down within the sidepanel
3. While scrolled down, click on any of the color picker options that are high up near the top of the window

Only way to fix appears to be closing and re-opening the client

![image](https://github.com/Skretzo/runelite-plugins/assets/45771962/229a8cb5-544d-4fb0-aec0-8944cb80ddec)

**Comment by b-licorice** [comment]
This may be of help:

https://github.com/runelite/runelite/commit/707ab78cdb6da090032c59f72e4ebfbc245126b1

**Comment by Skretzo** [comment]
This has now been fixed, and should be live in the client once it has been reviewed in 1-2 weeks.
