### ISSUE TITLE
Add config option to disable the sidebar icon [Radius markers, enhancement]

### ISSUE THREAD

**Issue by YvesW** [Skretzo/runelite-plugins#33]
I love using the plugin for e.g. Verzik nylos or Nex, but I've set up all my markers a long time ago. I'd love it if there was an option to disable the sidebar icon in the config.

**Comment by WhatTheHai** [comment]
Would love to see this!

**Comment by Skretzo** [comment]
This is planned for version 2.0

**Comment by YvesW** [comment]
Added in https://github.com/Skretzo/runelite-plugins/pull/43
