### ISSUE TITLE
Line markers prevents typing question marks in chat

### ISSUE THREAD

**Issue by rosekunkel** [Skretzo/runelite-plugins#35]
When I enable the line markers plugin on RuneLite I can no longer type question marks (?) in chat. Pressing `shift`+`/` should produce a question mark on my keyboard, but instead does nothing. Other characters/keys (capital letters, symbols, etc.) seem to be unaffected. The problem happens regardless of whether I use the left or right shift keys.

I asked a member of my clan to try to reproduce this issue and they could not, which leads me to believe it may be a macos-specific bug. The bug still happens if I switch to an otherwise-unmodified RuneLite profile, so I don't think it's a conflict between plugins from the plugin hub at least.

I'm able to build runelite and plugins locally on my machine, so I'd be happy to help test a fix. I tried reading the code but didn't see anything obvious that would cause a problem like this so I'm kind of at a loss.

```
14" 2023 MacBook Pro
Apple M2 Max chipset
macOS Ventura 13.5.2 (22G91)

RuneLite version: 1.10.13.2
OldSchool version: Rev 217
Launcher version: 2.6.8

Line Markers 1.1
```

**Comment by Skretzo** [comment]
Line Markers uses the shift key when creating new markers. The shift key is commonly used in other plugins too, such as the ground markers plugin. Do other plugins also prevent you from typing the question mark? (check with line markers disabled)

**Comment by rosekunkel** [comment]
No, it only seems to happen with line markers. Ground markers etc. work as expected and do not prevent me from typing `?` in chat.

**Comment by Skretzo** [comment]
Unlike Ground Markers the problem is that Line Markers needs to know both when you pressed the shift key and when you released the shift key. I have to use RuneLite's own keybind listener for this, and it apparently does not work correctly with your macos. I sadly do not know of a fix to this problem. Theoretically, I could detect your `/` key too and then programmatically type the `?` in the chat for you, but we are not allowed to do autotyping as that is considered as botting.

**Comment by Skretzo** [comment]
Does it happen with other `shift` + key combinations or only the `?`?

**Comment by Skretzo** [comment]
Can you also check if you have `shift` + `/` bound to something else in RuneLite? This can be checked with the `Debug Helper` plugin on the hub by opening its panel and clicking `Display Keybinds`

**Comment by rosekunkel** [comment]
These are my current keybinds. The list doesn't change when I enable or disable line markers.
```
Chat Commands Clear Single Word: ⌃+⌫
Key Remapping Camera Up key: W
Key Remapping Camera Down key: S
Key Remapping Camera Left key: A
Key Remapping Camera Right key: D
Key Remapping F1: 1
Key Remapping F2: 2
Key Remapping F3: 3
Key Remapping F4: 4
Key Remapping F5: 5
Key Remapping F6: 6
Key Remapping F7: 7
Key Remapping F8: 8
Key Remapping F9: 9
Key Remapping F10: 0
Key Remapping F11: -
Key Remapping F12: =
Key Remapping ESC: ⎋
Key Remapping Space: ␣
Key Remapping Control: ⌃
Ground Items Hotkey: ⌥
Bank Search Shortcut: ⌃+F
World Hopper Quick-hop previous: ⌃+⇧+←
World Hopper Quick-hop next: ⌃+⇧+→
```

**Comment by Skretzo** [comment]
> I'm able to build runelite and plugins locally on my machine, so I'd be happy to help test a fix.

I have made two potential fixes and would be happy if you could try both:

001fff25f2cfeb5394205407ef3c30261fa14514 checks for the shift key with a `KeyListener` instead of a `HotkeyListener`.

781fd5d0294cfae6137b9bd36cc2a621af1cce9e checks for the shift key in a client tick event instead of a `HotkeyListener`.

**Comment by rosekunkel** [comment]
I just tested and can confirm that both potential fixes work, so it's up to you which you prefer. Thank you!

**Comment by Skretzo** [comment]
Thank you. I will go with the `KeyListener` version, as that was recommended by one of the main RuneLite contributors. Plugin hub reviews typically take 1-2 weeks, so the change won't be live quite yet.

**Comment by Skretzo** [comment]
The review was quicker than expected, and the updated version is now live in the client.
