### ISSUE TITLE
Radius marker for zuk shield!

### ISSUE THREAD

**Issue by tuhk** [Skretzo/runelite-plugins#36]
Hello! i marked zuk shield in inferno with radius marker, the issue is that the radius marker is making cross, im trying to get it square, any ideas?

**Comment by Skretzo** [comment]
Change the attack type from `Melee` to `Ranged` or `Magic`:

![image](https://github.com/Skretzo/runelite-plugins/assets/53493631/40756d4e-0012-4edd-9c03-5847414918c7)
