### ISSUE TITLE
Video Recorder - Game Window Freezing

### ISSUE THREAD

**Issue by Rikardos87** [Skretzo/runelite-plugins#41]
Not sure what is happening but after like 3-5 seconds of recording the game window freezes and becomes unplayable, no errors or anything.
Runelite sidebar is still intractable so its not the client freezing , just the game window.
stopping recording don't unfreeze the game window, must close client to resolve.
[client.log](https://github.com/Skretzo/runelite-plugins/files/13423659/client.log)

**Comment by Skretzo** [comment]
This is a known issue related to the GPU plugin. RuneLite is very much not made for video recording (understandably) so it will conflict with the GPU plugin and/or 117HD plugin.

The best solution is to instead use a stand-alone program like Nvidia ShadowPlay or OBS to record videos.

Sadly, the only current RuneLite "solution" is to turn off both the GPU plugin and the 117HD plugin when you want to record a video with the plugin.

**Comment by Rikardos87** [comment]
Mabe adding this information to the Video Recorder side bar would be useful , cause I tried to find information on what could cause it and couldn't find anything.
