### ISSUE TITLE
Plugin Conflict: Identificator "Show menu info" +  Menu Entry Swapper "Use" 

### ISSUE THREAD

**Issue by DigammaZ** [Skretzo/runelite-plugins#47]
A recent update (~1 week ago) created a conflict between Menu Entry Swapper and Identificator

If the "Show menu info" is ticked in Identificator, you can no longer bind use to left-click nor shift-left-click.

This used to work until approximately one week ago.

**Comment by Skretzo** [comment]
Thank you for making me aware of this. I think I know how to fix this. I am curious, do you have the Identificator plugin enabled at all times? Personally I only turn the plugin on when I want to figure out an id and then turn it off again.

**Comment by Skretzo** [comment]
This should now be fixed in version 1.8.1.
Please let me know if the problem still persists after restarting your client.
