### ISSUE TITLE
NPC ID: FPS Issue

### ISSUE THREAD

**Issue by F5in** [Skretzo/runelite-plugins#48]
After a recent change, having NPC ID enabled with any of "Show ID", "Show index", or "Show name" enabled causes a very high FPS loss for me depending on the density of the area I'm in. I'm not 100% certain but I don't believe I was losing FPS with this plugin in the past, and I had it permanently enabled with "Show name" active. Including pictures with before and after (FPS is in top right corner, I have it locked at 150 max)
![image](https://github.com/Skretzo/runelite-plugins/assets/38023683/6cc9b15f-93cd-4273-9c74-23acde709f05)
![image](https://github.com/Skretzo/runelite-plugins/assets/38023683/747a5b3f-9b07-4a5f-a365-5d0a11cdd55a)

**Comment by Skretzo** [comment]
Can you please test if the FPS increases again if you disable the `Hide pets` option or `Hide random events` option? Those two options were added in the latest plugin update 1.3.2 and both/either are probably the culprit.

**Comment by F5in** [comment]
> Can you please test if the FPS increases again if you disable the `Hide pets` option or `Hide random events` option? Those two options were added in the latest plugin update 1.3.2 and both/either are probably the culprit.

Just tested with all combinations of options, the only things that lower my FPS are when any of the top 3 are enabled (`Show ID`, `Show index`, `Show name`)

**Comment by Skretzo** [comment]
I have now implemented a small fix and the new plugin version 1.3.3 is now live in the client (requires client restart). Could you please check if the FPS issue is fixed for you?

**Comment by F5in** [comment]
> I have now implemented a small fix and the new plugin version 1.3.3 is now live in the client (requires client restart). Could you please check if the FPS issue is fixed for you?

Apologies for the late reply, I forgot about it. As far as I can tell with my testing the FPS issue is fixed, thank you so much!
