### ISSUE TITLE
No Examine plugin seems to break bank tags for me

### ISSUE THREAD

**Issue by calvin079** [Skretzo/runelite-plugins#5]
Not sure if some of my other plugins that are messing with your plugin, but whenever I try to edit a tag for an item in my bank it tries to edit the tags for whatever item is in the first slot of my first tab. Unticking the box for "Inventory items" fixes this issue.

**Comment by Skretzo** [comment]
This issue should hopefully be fixed in [version 1.2](https://github.com/Skretzo/runelite-plugins/commit/4850ddc5b075c278cb9e72b0db89b257f8d5ff7c). Please let me know if the issue still persists.
