### ISSUE TITLE
Invalid Movement

### ISSUE THREAD

**Issue by MostlyPride** [Skretzo/runelite-plugins#50]
Invalid Movement works great the only issue is if you have 117 HD on and you've increased the render range. It basically highlights everything in a very large radius.  When it does this is tanks the FPS super hard in the client. 

![image](https://github.com/Skretzo/runelite-plugins/assets/10325931/aa49188b-8491-4cf3-869c-0c890f97d64b)

![image](https://github.com/Skretzo/runelite-plugins/assets/10325931/39d8738f-cbf2-4e00-a8f0-29b17f052fc4)

When in reality is just needs to render in about 10x10 around the character. I know this plugin has not been updated in 3 years. But I really enjoy it. 

I was wondering if we could had in the configuration for it a option to adjust how many tiles are rendered/highlighted around your characters.  <3

**Comment by Skretzo** [comment]
Adding a configuration option to only render in a radius around the player character is a very good idea!
I have added this suggestion as three config options `Scene radius`, `Minimap radius` and `World map radius` in plugin version 1.1. The new plugin version is now in review and will likely be live in the client in a week or two (edit: it is already live, but requires a client restart). Please let me know then if the FPS improves or not.

**Comment by MostlyPride** [comment]
Thank you so much! I can't wait to fully test it out!
