### ISSUE TITLE
Suggestion: Keep Examine option if entity has no other options [No Examine]

### ISSUE THREAD

**Issue by Voiture-0** [Skretzo/runelite-plugins#53]
I love this plugin for reducing the noise in the right click menu. One reason I sometimes disable it is when I am curious what something is, but it has no interaction options. For example: decorative Objects like flowers and decorative NPCs like little rabbit or other critters.

I would love if there is a config option (similar to the checkboxes for NPCs & Objects) that can allow leaving the Examine option if an NPC or Object has no other options. Preferably a separate checkbox for each, as I would like this for NPCs but I would probably not care for Objects.

**Comment by Skretzo** [comment]
This was added in plugin version 1.5 as config options `Keep lonely NPC examines` and `Keep lonely object examines`

**Comment by Voiture-0** [comment]
Thank you!! awesome I love it <3
