### ISSUE TITLE
[Feature Request] Remove cancel

### ISSUE THREAD

**Issue by SandroVA** [Skretzo/runelite-plugins#7]
Any chance you can also remove the cancel option from the right click menu?

**Comment by Skretzo** [comment]
I will give it a try, but I know cancel is a special case so unsure if it will work. I should probably also be a bit careful as removing the examine option caused some unexpected issues in another plugin, so I will properly fix those first.

**Comment by SandroVA** [comment]
Awesome. Thanks for trying! Good luck :)

**Comment by Skretzo** [comment]
This was added in [version 1.3](https://github.com/Skretzo/runelite-plugins/commit/d4c348cdc5cbd8ed57b6a953fd2b49c484115979), and is now live in the client.
