### ISSUE TITLE
Issue with Shift-click Object & NPC Custom Swapping

### ISSUE THREAD

**Issue by SaffiCauthon** [Skretzo/runelite-plugins#9]
Enabling the plugin disables new features in 1.8.25

![Plugin Failure](https://i.imgur.com/kt2SsJu.gif)

menu swapper: add custom shift-click npc swap:
https://github.com/runelite/runelite/commit/9d69c84653fee0eabe7c7686c3124be8d4b0bb56

menu swapper: add custom shift-click object swap:
https://github.com/runelite/runelite/commit/a9d89f058b73f03bbf4b60b9cbfb85db383d716f

**Comment by Skretzo** [comment]
Thank you for raising this issue. I am aware of this problem and will look into fixing this soon when I get some time.

**Comment by Skretzo** [comment]
Should be fixed in [version 1.2](https://github.com/Skretzo/runelite-plugins/commit/4850ddc5b075c278cb9e72b0db89b257f8d5ff7c). Please let me know if the issue still persists.
